[package]
name = "robustloader"
version = "0.1.0"
authors = ["talbor49 <talbor49@gmail.com>", "DanielEliad <daniel.eliad32@gmail.com>", "RoyShulman <roy.shulman@gmail.com>"]
edition = "2019"

[dependencies]
